- name: Initial configuration of a server.
  hosts: servers
  user: deploy
  vars_files:
    - server-template-vars.yml
  roles:
    - role: ansible-initial-server
      vars:
        iserver_user: deploy
